//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetesPredictionApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public double PlasmaGlucose { get; set; }
        public double DistolicBlood { get; set; }
        public double TricepsSFT { get; set; }
        public double SerumInsuline2Hour { get; set; }
        public double BodyMassIndex { get; set; }
        public double DiabetesPedigreeFunction { get; set; }
        public int Age { get; set; }
        public Nullable<decimal> ProbabilityOfDiabetes { get; set; }
        public int TimesPregnant { get; set; }
        public string State { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
